#run by $python DIFF_dag_data.py --config DIFF_dag34.yaml
# misc
random_seed: 1234
scheduler_type: cp
split: test_greedy
save_dir: "../data/shared/huiyuan/dag_combo34/compare"

# dag generation
load_graph: 72
#specify one of the following two
combo34: true
#combo52: true

resource_limit: 600

# add edge config
add_edge: true
addedge_per_graph: 10
max_add: 5
num_workers: 12
test_addedge: true



