#run by $python DIFF_dag_data.py --config DIFF_dag.yaml
# misc
random_seed: 1234
scheduler_type: cp
split: val
save_dir: "/data/shared/huiyuan/dag52_addedge5"
#save_dir: "/data/shared/huiyuan/dag25_addedge20"

# dag generation
load_graph: 128
#specify one of the following two
combo52: true
#num_init_dags: 25

resource_limit: 6000
resource_scale: 20.0

# add edge config
# add_edge: true
addedge_per_graph: 32
max_add: 5
num_workers: 50



