#run by $python DIFF_dag_data.py --config DIFF_dag.yaml
# misc
random_seed: 1234
scheduler_type: cp
split: train
save_dir: "../data/shared/huiyuan/dag_combo/dag52_addedge10_rescale"

# dag generation
load_graph: 1000
#specify one of the following two
combo52: true
#num_init_dags: 25

resource_limit: 6000
resource_scale: 20.0

# add edge config
add_edge: true
addedge_per_graph: 32
max_add: 10
num_workers: 50



